main: me.cluter.trails.Main
author: cluter123
name: PlayerTrails
version: 1.2
description: Gives players trails! :D

commands:
  playertrails:
    description: Reloads the plugin.
  trail:
    description: Turns the trail on or off - without the need of an inventory item.
    
permissions:
  trail.use:
    description: Allows trails
  trail.reload:
    description: Reloads the plugin.
  trail.command:
    description: Toggles on the trail without an inventory item.